### ISSUE TITLE
Build pkgdown website using Github Actions

### ISSUE THREAD

**Issue by jepusto** [jepusto/lmeInfo#31]
Consider using Github Actions to build the pkgdown website. Read more about this here:
- https://ropenscilabs.github.io/actions_sandbox/
- https://github.com/r-lib/actions

**Comment by manchen07** [comment]
I tweaked the pkgdown.yaml based on the following source:

- https://github.com/r-lib/pkgdown/blob/master/.github/workflows/pkgdown.yaml
- https://github.com/r-lib/actions/blob/master/examples/pkgdown.yaml

They did not point out that we need to add a default cran mirror when installing the remotes packages: install.packages('remotes', repos = "http://cran.us.r-project.org")

The pkgdown using Github Actions is working now. Could you please go to Settings and change the source of GitHub Pages to gh-pages branch? Thanks!

**Comment by jepusto** [comment]
Done. It looks like it deployed. Does this mean we can remove the /docs folder from the master branch?
