### ISSUE TITLE
Doesn't install on R 4.0.x

### ISSUE THREAD

**Issue by rogerssam** [jepusto/lmeInfo#46]
Hello,
I'm just wondering if you could explain why the package depends on R >= 4.1? 
I am the developer of the package [biometryassist](https://github.com/biometryhub/biometryassist/). It turns out that your package is a cascaded dependency from another package that biometryassist imports. I understand the complications with dependencies and R versions, but would it be possible for you to re-add for support for R4.0?
Many thanks,
Sam

**Comment by jepusto** [comment]
R 4.1 introduced the native pipe (`|>`), which we use in some of our tests. I can consider reworking the tests so that we don't use pipes. Could you provide some more information about your need to support R < 4.1?

**Comment by rogerssam** [comment]
Many thanks for your response. That makes sense. I have cloned the repo and reworked the test file with pipes, and confirmed the tests still pass on R 4.0.0.

The problem that I encounter is people who are hesitant to update R + packages because it can be fragile, especially for novice users. So I try to aim to support a few of the most recent versions to give people at least a couple of years of stability.

Would you accept a pull request for this? I am happy to submit one next week to close this issue if that's ok with you?

**Comment by jepusto** [comment]
Yes, happy to take a PR. However, we just submitted an update to lmeInfo on 7/7, so I want to wait another few weeks (until 8/7 at least) before sending another submission to CRAN. Just to set expectations.

**Comment by rogerssam** [comment]
Great, thanks again.
I completely understand re submitting to CRAN.
