### ISSUE TITLE
Applying the delta rule to estimate the sampling variance of the variance component parameters like `varcomp_vcov` in a simple case 

### ISSUE THREAD

**Issue by gavril0** [jepusto/lmeInfo#54]
I have tried to compute the variance-covariance matrix of the sample parameters of the random effects for a model fitted with `lme`.  In particular, I tried to use the delta rule to transform the terms in the diagonals of the matrix `apVar` which contain the sampling variance of the variance component  parameters in the so-called natural parameterization ([Pinheiro, p. 93](https://books.google.it/books?redir_esc=y&hl=it&id=y54QDUTmvDcC&q=p.+93#v=onepage&q=natural%20parameterization&f=false)) in a simple case (two correlated random effects).  However, i get a a result that is different from the one obtained with `lmeInfo::varcomp_vcov` for the variance of the sample covariance. Unfortunately, this [page](https://stats.oarc.ucla.edu/r/faq/how-can-i-calculate-standard-errors-for-variance-components-from-mixed-models/) does not show how to apply the delta rule for the variance of the sample covariance parameter. 

I posted my [question](https://stats.stackexchange.com/questions/631633/reparameterization-of-the-variance-covariance-matrix-apvar-of-the-random-eff#mjx-eqn-2
)  on stats.stackexchange with the code that I am using to reparameterize the matrix `apVar`.  The code is quite simple but also currently limited to two correlated random effects.   Because the results are very similar for the variance of the sample variance parameters, I think that I must have made an error somewhere when trying to use the delta method to compute the variance of the sample covariance parameter and I hope that somebody will find it. 

 Thank you for your useful package, which provides much more comprehensive functions to resolve the problem.

**Comment by jepusto** [comment]
Closing because this is not an issue with `lmeInfo`.
